name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      uses: crystal-lang/install-crystal@v1

    - name: Cache shards
      uses: actions/cache@v4
      with:
        path: lib
        key: ${{ runner.os }}-shards-${{ hashFiles('**/shard.lock') }}

    - name: Install shards
      run: shards check || shards install

    # Build debug release and check code quality on one platform

    - name: Setup debug environment
      if: runner.os == 'linux-latest'
      run: mkdir -p bin/debug

    - name: Build Debug
      if: runner.os == 'linux-latest'
      run: SHARDS_BIN_PATH=bin/debug shards build --debug

    - name: Check formatting
      if: runner.os == 'linux-latest'
      run: crystal tool format; git diff --exit-code

    # Build releases on all platforms

    - name: Setup release environment
      run: mkdir -p bin/release

    - name: Build Release
      run: SHARDS_BIN_PATH=bin/release shards build --release


    # - name: Run Linting
    #   run: bin/ameba --all src/


    # You can add custom test run commands specific to your tests here
    # - name: Run tests
    #   run: ops run_test_command
