name: Build and Publish Enkaidu Container Image

on:
  create:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-test'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # ------ Do all the platform independent work once

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1

      - name: Install Node
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Cache shards
        uses: actions/cache@v4
        with:
          path: |
            lib
          key: ${{ runner.os }}-shards-${{ hashFiles('**/shard.lock') }}

      - name: Install shards
        run: shards --production check || shards --production install

      - name: Prepare and build webui
        run: |
          cd webui
          npm i
          npm run build
          cd ..

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version from shard.yml
        id: extract_version
        run: |
          VERSION=$(grep -E '^version:' shard.yml | awk '{print $2}')
          if [ -z "$VERSION" ]; then
            echo "Error: No version found in shard.yml"
            exit 1
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      # ----- Now build the multi-platform container image

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Containerfile_GHA
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/enkaidu:${{ steps.extract_version.outputs.version }}
            ${{ secrets.DOCKER_USERNAME }}/enkaidu:latest
          labels: |
            org.opencontainers.image.version=${{ steps.extract_version.outputs.version }}
